# flake8: noqa
from multiprocessing import Pool
from classify import do_classification
import settings
import numpy as np

PROCESSES = 6
DEFAULT_EEG_BANDS = {'Delta': (0, 4),
                     'Theta': (4, 8),
                     'Alpha': (8, 12),
                     'Beta': (12, 30),
                     'Gamma': (30, 45)}
global passive, passive_fourier, passive_fourier_append, active, active_fourier, active_fourier_append

force_training = False

sensor_cols = ["X1", "X2", "X3", "CM", "O1", "O2", "A1", "A2", "Fp1", "Fp2", "T5", "T6", "F7", "F8", "T3", "T4", "P3", "P4", "F3", "F4", "Cz", "Fz", "C3", "C4"]
all_cols = settings.DROP_COLUMNS + sensor_cols


#drop_cols_20 = [*settings.DROP_COLUMNS, "X1", "X2", "X3", "CM"]
#drop_cols_16 = [*settings.DROP_COLUMNS, "X1", "X2", "X3", "CM", "O2", "A1", "A2", "O1"]
#drop_cols_12 = [*drop_cols_16, "Fp1", "Fp2", "T5", "T6"]
#drop_cols_9 = [*drop_cols_12, "F7", "F8", "T3"]
#drop_cols_6 = [*drop_cols_12, "F7", "F8", "T3", "CM", "P3", "P4"]
#drop_cols_4 = [*drop_cols_6, "F3", "F4"]
#drop_cols_3 = [*drop_cols_6, "F3", "F4", "Cz"]
drop_cols_20 = [*settings.DROP_COLUMNS, "Fp2", "T5", "C3", "T4"]
drop_cols_16 = [*drop_cols_20, "CM", "X1", "X2", "X3"]
drop_cols_12 = [*drop_cols_16, "Fp1", "T6", "C4", "T3"]
drop_cols_9 = [*drop_cols_12, "A1", "A2", "Cz"]
drop_cols_6 = [*drop_cols_9, "O1", "O2", "Fz"]
drop_cols_4 = [*drop_cols_6, "P3", "P4"]
drop_cols_3 = [*drop_cols_9, "O1", "O2", "P3", "P4", "F7", "F8"]

front_4 = ["Fp1", "F3", "Fz", "F4"]
front_2 = ["F3", "F4"]
left_4 = ["F7", "T3", "A1", "P3"]
left_2 = ["A1", "T3"]
right_4 = ["F8", "C4", "T6", "A2"]
right_2 = ["A2", "T6"]
back_4 = ["P3", "P4", "O1", "O2"]
back_2 = ["O1", "O2"]


def linear_band_generator(num_bands, lower_bound=0, upper_bound=45, band_prefix='band_'):
    band_boundaries = np.linspace(lower_bound, upper_bound, num_bands + 1)

    bands = {}
    for index in range(num_bands):
        bands[band_prefix + str(index + 1)] = (band_boundaries[index], band_boundaries[index + 1])

    return bands

def eeg_band_generator(num_bands):
    if num_bands % 5 != 0:
        return linear_band_generator(num_bands)
    
    band_expansion = num_bands // 5

    bands = {}
    for key in DEFAULT_EEG_BANDS.keys():
        band = DEFAULT_EEG_BANDS[key]
        result = linear_band_generator(band_expansion, lower_bound=band[0], upper_bound=band[1], band_prefix=key + "_")
        bands.update(result)
    
    return bands

def get_only_sensors(sensors, model_name, num_columns, num_rows):
    labels = ['active', 'passive']

    drop_cols = settings.DROP_COLUMNS.copy()
    i = 0
    for col in sensor_cols:
        i += 1
        if col not in sensors:
            drop_cols.append(col)

    results = []
    for label in labels:
        name = "{0}_{1}".format(label, model_name)
        results.append((name, {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":('_data_' + label), "model_file_name":(name+'.h5'), "model_weights_file_name":(name+'_weights.h5'), "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols, "num_columns":num_columns, "num_rows":num_rows}))
        name = "{0}_{1}_fourier".format(label, model_name)
        results.append((name, {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":('_data_' + label), "model_file_name":(name+'.h5'), "model_weights_file_name":(name+'_weights.h5'), "use_fourier":True,  "fourier_append":False, "drop_columns":drop_cols, "num_columns":num_columns, "num_rows":num_rows}))
        name = "{0}_{1}_fourier_append".format(label, model_name)
        results.append((name, {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":('_data_' + label), "model_file_name":(name+'.h5'), "model_weights_file_name":(name+'_weights.h5'), "use_fourier":True,  "fourier_append":True,  "drop_columns":drop_cols, "num_columns":num_columns, "num_rows":num_rows}))
    
    return results

expanded_eeg_bands_7 =  eeg_band_generator(7)
expanded_eeg_bands_10 = eeg_band_generator(10)
expanded_eeg_bands_12 = eeg_band_generator(12)
expanded_eeg_bands_15 = eeg_band_generator(15)
expanded_eeg_bands_17 = eeg_band_generator(17)
expanded_eeg_bands_20 = eeg_band_generator(20)
expanded_eeg_bands_22 = eeg_band_generator(22)
expanded_eeg_bands_25 = eeg_band_generator(25)
expanded_eeg_bands_27 = eeg_band_generator(27)
expanded_eeg_bands_30 = eeg_band_generator(30)
expanded_eeg_bands_40 = eeg_band_generator(40)
expanded_eeg_bands_50 = eeg_band_generator(50)
expanded_eeg_bands_60 = eeg_band_generator(60)
expanded_eeg_bands_70 = eeg_band_generator(70)
expanded_eeg_bands_80 = eeg_band_generator(80)
expanded_eeg_bands_90 = eeg_band_generator(90)
expanded_eeg_bands_92 = eeg_band_generator(92)
expanded_eeg_bands_95 = eeg_band_generator(95)
expanded_eeg_bands_97 = eeg_band_generator(97)
expanded_eeg_bands_100 = eeg_band_generator(100)
expanded_eeg_bands_102 = eeg_band_generator(102)
expanded_eeg_bands_105 = eeg_band_generator(105)
expanded_eeg_bands_107 = eeg_band_generator(107)
expanded_eeg_bands_110 = eeg_band_generator(110)

# Setup Args

mixed_model_args = [
    ("passive",                         {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive.h5',                           "model_weights_file_name":'passive_weights.h5',                         "use_fourier":False, "fourier_append":False}),
#    ("passive_fourier",                 {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier.h5',                   "model_weights_file_name":'passive_fourier_weights.h5',                 "use_fourier":True,  "fourier_append":False}),
#    ("passive_fourier_append",          {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_append.h5',            "model_weights_file_name":'passive_fourier_append_weights.h5',          "use_fourier":True,  "fourier_append":True}),
#    ("passive_fourier_expanded",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded.h5',          "model_weights_file_name":'passive_fourier_expanded_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_20}),
#    ("passive_fourier_expanded_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_append.h5',   "model_weights_file_name":'passive_fourier_expanded_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_20}),
    ("passive_20_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_20_col.h5',                    "model_weights_file_name":'passive_20_col_weights.h5',                  "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_20, "num_columns":5, "num_rows":4}),
    ("passive_16_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_16_col.h5',                    "model_weights_file_name":'passive_16_col_weights.h5',                  "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_16, "num_columns":4, "num_rows":4}),
    ("passive_12_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_12_col.h5',                    "model_weights_file_name":'passive_12_col_weights.h5',                  "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_12, "num_columns":4, "num_rows":3}),
    ("passive_09_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_9_col.h5',                     "model_weights_file_name":'passive_9_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_9,  "num_columns":3, "num_rows":3}),
    ("passive_06_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_6_col.h5',                     "model_weights_file_name":'passive_6_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_6,  "num_columns":3, "num_rows":2}),
    ("passive_04_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_4_col.h5',                     "model_weights_file_name":'passive_4_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_4,  "num_columns":2, "num_rows":2}),
    ("passive_03_col",                  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_passive', "model_file_name":'passive_3_col.h5',                     "model_weights_file_name":'passive_3_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_3,  "num_columns":3, "num_rows":1}),
    ("active",                          {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active.h5',                            "model_weights_file_name":'active_weights.h5',                          "use_fourier":False, "fourier_append":False}),
#    ("active_fourier",                  {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier.h5',                    "model_weights_file_name":'active_fourier_weights.h5',                  "use_fourier":True,  "fourier_append":False}),
#    ("active_fourier_append",           {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_append.h5',             "model_weights_file_name":'active_fourier_append_weights.h5',           "use_fourier":True,  "fourier_append":True}),
#    ("active_fourier_expanded",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded.h5',           "model_weights_file_name":'active_fourier_expanded_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_20}),
#    ("active_fourier_expanded_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_append.h5',    "model_weights_file_name":'active_fourier_expanded_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_20}),
    ("active_20_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_20_col.h5',                     "model_weights_file_name":'active_20_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_20, "num_columns":5, "num_rows":4}),
    ("active_16_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_16_col.h5',                     "model_weights_file_name":'active_16_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_16, "num_columns":4, "num_rows":4}),
    ("active_12_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_12_col.h5',                     "model_weights_file_name":'active_12_col_weights.h5',                   "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_12, "num_columns":4, "num_rows":3}),
    ("active_09_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_9_col.h5',                      "model_weights_file_name":'active_9_col_weights.h5',                    "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_9,  "num_columns":3, "num_rows":3}),
    ("active_06_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_6_col.h5',                      "model_weights_file_name":'active_6_col_weights.h5',                    "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_6,  "num_columns":3, "num_rows":2}),
    ("active_04_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_4_col.h5',                      "model_weights_file_name":'active_4_col_weights.h5',                    "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_4,  "num_columns":2, "num_rows":2}),
    ("active_03_col",                   {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":20,  "data_location":'_data_active',  "model_file_name":'active_3_col.h5',                      "model_weights_file_name":'active_3_col_weights.h5',                    "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols_3,  "num_columns":3, "num_rows":1})
]

fourier_band_model_args = [
    ("passive_fourier",                     {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier.h5',                      "model_weights_file_name":'passive_fourier_weights.h5',                    "use_fourier":True,  "fourier_append":False}),
    ("passive_fourier_append",              {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_append.h5',               "model_weights_file_name":'passive_fourier_append_weights.h5',             "use_fourier":True,  "fourier_append":True}),
    ("passive_fourier_expanded_007",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_7.h5',           "model_weights_file_name":'passive_fourier_expanded_7_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_7}),
    ("passive_fourier_expanded_007_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_7_append.h5',    "model_weights_file_name":'passive_fourier_expanded_7_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_7}),
    ("passive_fourier_expanded_010",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_10.h5',          "model_weights_file_name":'passive_fourier_expanded_10_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_10}),
    ("passive_fourier_expanded_010_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_10_append.h5',   "model_weights_file_name":'passive_fourier_expanded_10_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_10}),
    ("passive_fourier_expanded_012",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_12.h5',          "model_weights_file_name":'passive_fourier_expanded_12_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_12}),
    ("passive_fourier_expanded_012_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_12_append.h5',   "model_weights_file_name":'passive_fourier_expanded_12_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_12}),
    ("passive_fourier_expanded_015",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_15.h5',          "model_weights_file_name":'passive_fourier_expanded_15_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_15}),
    ("passive_fourier_expanded_015_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_15_append.h5',   "model_weights_file_name":'passive_fourier_expanded_15_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_15}),
    ("passive_fourier_expanded_017",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_17.h5',          "model_weights_file_name":'passive_fourier_expanded_17_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_17}),
    ("passive_fourier_expanded_017_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_17_append.h5',   "model_weights_file_name":'passive_fourier_expanded_17_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_17}),
    ("passive_fourier_expanded_020",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_20.h5',          "model_weights_file_name":'passive_fourier_expanded_20_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_20}),
    ("passive_fourier_expanded_020_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_20_append.h5',   "model_weights_file_name":'passive_fourier_expanded_20_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_20}),
    ("passive_fourier_expanded_022",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_22.h5',          "model_weights_file_name":'passive_fourier_expanded_22_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_22}),
    ("passive_fourier_expanded_022_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_22_append.h5',   "model_weights_file_name":'passive_fourier_expanded_22_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_22}),
    ("passive_fourier_expanded_025",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_25.h5',          "model_weights_file_name":'passive_fourier_expanded_25_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_25}),
    ("passive_fourier_expanded_025_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_25_append.h5',   "model_weights_file_name":'passive_fourier_expanded_25_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_25}),
    ("passive_fourier_expanded_027",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_27.h5',          "model_weights_file_name":'passive_fourier_expanded_27_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_27}),
    ("passive_fourier_expanded_027_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_27_append.h5',   "model_weights_file_name":'passive_fourier_expanded_27_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_27}),
    ("passive_fourier_expanded_030",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_30.h5',          "model_weights_file_name":'passive_fourier_expanded_30_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_30}),
    ("passive_fourier_expanded_030_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_30_append.h5',   "model_weights_file_name":'passive_fourier_expanded_30_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_30}),
    ("passive_fourier_expanded_040",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_40.h5',          "model_weights_file_name":'passive_fourier_expanded_40_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_40}),
    ("passive_fourier_expanded_040_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_40_append.h5',   "model_weights_file_name":'passive_fourier_expanded_40_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_40}),
    ("passive_fourier_expanded_050",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_50.h5',          "model_weights_file_name":'passive_fourier_expanded_50_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_50}),
    ("passive_fourier_expanded_050_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_50_append.h5',   "model_weights_file_name":'passive_fourier_expanded_50_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_50}),
    ("passive_fourier_expanded_060",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_60.h5',          "model_weights_file_name":'passive_fourier_expanded_60_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_60}),
    ("passive_fourier_expanded_060_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_60_append.h5',   "model_weights_file_name":'passive_fourier_expanded_60_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_60}),
    ("passive_fourier_expanded_070",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_70.h5',          "model_weights_file_name":'passive_fourier_expanded_70_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_70}),
    ("passive_fourier_expanded_070_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_70_append.h5',   "model_weights_file_name":'passive_fourier_expanded_70_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_70}),
    ("passive_fourier_expanded_080",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_80.h5',          "model_weights_file_name":'passive_fourier_expanded_80_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_80}),
    ("passive_fourier_expanded_080_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_80_append.h5',   "model_weights_file_name":'passive_fourier_expanded_80_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_80}),
    ("passive_fourier_expanded_090",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_90.h5',          "model_weights_file_name":'passive_fourier_expanded_90_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_90}),
    ("passive_fourier_expanded_090_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_90_append.h5',   "model_weights_file_name":'passive_fourier_expanded_90_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_90}),
    ("passive_fourier_expanded_092",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_92.h5',          "model_weights_file_name":'passive_fourier_expanded_92_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_92}),
    ("passive_fourier_expanded_092_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_92_append.h5',   "model_weights_file_name":'passive_fourier_expanded_92_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_92}),
    ("passive_fourier_expanded_095",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_95.h5',          "model_weights_file_name":'passive_fourier_expanded_95_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_95}),
    ("passive_fourier_expanded_095_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_95_append.h5',   "model_weights_file_name":'passive_fourier_expanded_95_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_95}),
    ("passive_fourier_expanded_097",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_97.h5',          "model_weights_file_name":'passive_fourier_expanded_97_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_97}),
    ("passive_fourier_expanded_097_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_97_append.h5',   "model_weights_file_name":'passive_fourier_expanded_97_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_97}),
    ("passive_fourier_expanded_100",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_100.h5',          "model_weights_file_name":'passive_fourier_expanded_100_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_100}),
    ("passive_fourier_expanded_100_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_100_append.h5',   "model_weights_file_name":'passive_fourier_expanded_100_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_100}),
    ("passive_fourier_expanded_102",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_102.h5',          "model_weights_file_name":'passive_fourier_expanded_102_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_102}),
    ("passive_fourier_expanded_102_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_102_append.h5',   "model_weights_file_name":'passive_fourier_expanded_102_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_102}),
    ("passive_fourier_expanded_105",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_105.h5',          "model_weights_file_name":'passive_fourier_expanded_105_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_105}),
    ("passive_fourier_expanded_105_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_105_append.h5',   "model_weights_file_name":'passive_fourier_expanded_105_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_105}),
    ("passive_fourier_expanded_107",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_107.h5',          "model_weights_file_name":'passive_fourier_expanded_107_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_107}),
    ("passive_fourier_expanded_107_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_107_append.h5',   "model_weights_file_name":'passive_fourier_expanded_107_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_107}),
    ("passive_fourier_expanded_110",        {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_110.h5',          "model_weights_file_name":'passive_fourier_expanded_110_weights.h5',        "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_110}),
    ("passive_fourier_expanded_110_append", {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_passive', "model_file_name":'passive_fourier_expanded_110_append.h5',   "model_weights_file_name":'passive_fourier_expanded_110_append_weights.h5', "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_110}),
    ("active_fourier",                      {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier.h5',                       "model_weights_file_name":'active_fourier_weights.h5',                     "use_fourier":True,  "fourier_append":False}),
    ("active_fourier_append",               {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_append.h5',                "model_weights_file_name":'active_fourier_append_weights.h5',              "use_fourier":True,  "fourier_append":True}),
    ("active_fourier_expanded_007",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_7.h5',            "model_weights_file_name":'active_fourier_expanded_7_weights.h5',          "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_7}),
    ("active_fourier_expanded_007_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_7_append.h5',     "model_weights_file_name":'active_fourier_expanded_7_append_weights.h5',   "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_7}),
    ("active_fourier_expanded_010",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_10.h5',           "model_weights_file_name":'active_fourier_expanded_10_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_10}),
    ("active_fourier_expanded_010_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_10_append.h5',    "model_weights_file_name":'active_fourier_expanded_10_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_10}),
    ("active_fourier_expanded_012",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_12.h5',           "model_weights_file_name":'active_fourier_expanded_12_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_12}),
    ("active_fourier_expanded_012_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_12_append.h5',    "model_weights_file_name":'active_fourier_expanded_12_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_12}),
    ("active_fourier_expanded_015",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_15.h5',           "model_weights_file_name":'active_fourier_expanded_15_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_15}),
    ("active_fourier_expanded_015_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_15_append.h5',    "model_weights_file_name":'active_fourier_expanded_15_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_15}),
    ("active_fourier_expanded_017",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_17.h5',           "model_weights_file_name":'active_fourier_expanded_17_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_17}),
    ("active_fourier_expanded_017_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_17_append.h5',    "model_weights_file_name":'active_fourier_expanded_17_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_17}),
    ("active_fourier_expanded_020",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_20.h5',           "model_weights_file_name":'active_fourier_expanded_20_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_20}),
    ("active_fourier_expanded_020_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_20_append.h5',    "model_weights_file_name":'active_fourier_expanded_20_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_20}),
    ("active_fourier_expanded_022",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_22.h5',           "model_weights_file_name":'active_fourier_expanded_22_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_22}),
    ("active_fourier_expanded_022_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_22_append.h5',    "model_weights_file_name":'active_fourier_expanded_22_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_22}),
    ("active_fourier_expanded_025",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_25.h5',           "model_weights_file_name":'active_fourier_expanded_25_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_25}),
    ("active_fourier_expanded_025_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_25_append.h5',    "model_weights_file_name":'active_fourier_expanded_25_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_25}),
    ("active_fourier_expanded_027",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_27.h5',           "model_weights_file_name":'active_fourier_expanded_27_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_27}),
    ("active_fourier_expanded_027_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_27_append.h5',    "model_weights_file_name":'active_fourier_expanded_27_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_27}),
    ("active_fourier_expanded_030",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_30.h5',           "model_weights_file_name":'active_fourier_expanded_30_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_30}),
    ("active_fourier_expanded_030_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_30_append.h5',    "model_weights_file_name":'active_fourier_expanded_30_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_30}),
    ("active_fourier_expanded_040",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_40.h5',           "model_weights_file_name":'active_fourier_expanded_40_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_40}),
    ("active_fourier_expanded_040_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_40_append.h5',    "model_weights_file_name":'active_fourier_expanded_40_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_40}),
    ("active_fourier_expanded_050",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_50.h5',           "model_weights_file_name":'active_fourier_expanded_50_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_50}),
    ("active_fourier_expanded_050_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_50_append.h5',    "model_weights_file_name":'active_fourier_expanded_50_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_50}),
    ("active_fourier_expanded_060",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_60.h5',           "model_weights_file_name":'active_fourier_expanded_60_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_60}),
    ("active_fourier_expanded_060_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_60_append.h5',    "model_weights_file_name":'active_fourier_expanded_60_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_60}),
    ("active_fourier_expanded_070",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_70.h5',           "model_weights_file_name":'active_fourier_expanded_70_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_70}),
    ("active_fourier_expanded_070_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_70_append.h5',    "model_weights_file_name":'active_fourier_expanded_70_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_70}),
    ("active_fourier_expanded_080",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_80.h5',           "model_weights_file_name":'active_fourier_expanded_80_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_80}),
    ("active_fourier_expanded_080_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_80_append.h5',    "model_weights_file_name":'active_fourier_expanded_80_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_80}),
    ("active_fourier_expanded_090",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_90.h5',           "model_weights_file_name":'active_fourier_expanded_90_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_90}),
    ("active_fourier_expanded_090_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_90_append.h5',    "model_weights_file_name":'active_fourier_expanded_90_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_90}),
    ("active_fourier_expanded_092",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_92.h5',           "model_weights_file_name":'active_fourier_expanded_92_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_92}),
    ("active_fourier_expanded_092_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_92_append.h5',    "model_weights_file_name":'active_fourier_expanded_92_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_92}),
    ("active_fourier_expanded_095",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_95.h5',           "model_weights_file_name":'active_fourier_expanded_95_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_95}),
    ("active_fourier_expanded_095_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_95_append.h5',    "model_weights_file_name":'active_fourier_expanded_95_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_95}),
    ("active_fourier_expanded_097",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_97.h5',           "model_weights_file_name":'active_fourier_expanded_97_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_97}),
    ("active_fourier_expanded_097_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_97_append.h5',    "model_weights_file_name":'active_fourier_expanded_97_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_97}),
    ("active_fourier_expanded_100",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_100.h5',           "model_weights_file_name":'active_fourier_expanded_100_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_100}),
    ("active_fourier_expanded_100_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_100_append.h5',    "model_weights_file_name":'active_fourier_expanded_100_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_100}),
    ("active_fourier_expanded_102",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_102.h5',           "model_weights_file_name":'active_fourier_expanded_102_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_102}),
    ("active_fourier_expanded_102_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_102_append.h5',    "model_weights_file_name":'active_fourier_expanded_102_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_102}),
    ("active_fourier_expanded_105",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_105.h5',           "model_weights_file_name":'active_fourier_expanded_105_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_105}),
    ("active_fourier_expanded_105_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_105_append.h5',    "model_weights_file_name":'active_fourier_expanded_105_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_105}),
    ("active_fourier_expanded_107",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_107.h5',           "model_weights_file_name":'active_fourier_expanded_107_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_107}),
    ("active_fourier_expanded_107_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_107_append.h5',    "model_weights_file_name":'active_fourier_expanded_107_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_107}),
    ("active_fourier_expanded_110",         {"force_training":force_training, "max_epochs":100, "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_110.h5',           "model_weights_file_name":'active_fourier_expanded_110_weights.h5',         "use_fourier":True,  "fourier_append":False, "fourier_eeg_bands":expanded_eeg_bands_110}),
    ("active_fourier_expanded_110_append",  {"force_training":force_training, "max_epochs":20,  "early_stopping":False, "batch_size":32, "frames_per_timeslice":300, "data_location":'_data_active',  "model_file_name":'active_fourier_expanded_110_append.h5',    "model_weights_file_name":'active_fourier_expanded_110_append_weights.h5',  "use_fourier":True,  "fourier_append":True,  "fourier_eeg_bands":expanded_eeg_bands_110}),
]

localized_sensor_model_args = []
localized_sensor_model_args.extend(get_only_sensors(front_4, "spacial_front_4", 2, 2))
localized_sensor_model_args.extend(get_only_sensors(front_2, "spacial_front_2", 2, 1))
localized_sensor_model_args.extend(get_only_sensors(left_4, "spacial_left_4", 2, 2))
localized_sensor_model_args.extend(get_only_sensors(left_2, "spacial_left_2", 2, 1))
localized_sensor_model_args.extend(get_only_sensors(right_4, "spacial_right_4", 2, 2))
localized_sensor_model_args.extend(get_only_sensors(right_2, "spacial_right_2", 2, 1))
localized_sensor_model_args.extend(get_only_sensors(back_4, "spacial_back_4", 2, 2))
localized_sensor_model_args.extend(get_only_sensors(back_2, "spacial_back_2", 2, 1))

all_tests = []
all_tests.extend(mixed_model_args)
all_tests.extend(fourier_band_model_args)
all_tests.extend(localized_sensor_model_args)

print("Will run " + str(len(all_tests)) + " tests")

"""
# SEE all_sensors.txt

labels = ['active', 'passive']
for label in labels:
    for col in sensor_cols:
        name = "{0}_{1}".format(label, col)
        index = all_cols.index(col)
        drop_cols = all_cols[:index] + all_cols[index + 1:]
        #print("name: " + name)
        model_args.append((name, {"force_training":force_training, "max_epochs":20, "early_stopping":False, "batch_size":32, "frames_per_timeslice":20, "data_location":('_data_' + label), "model_file_name":(name+'.h5'), "model_weights_file_name":(name+'_weights.h5'), "use_fourier":False, "fourier_append":False, "drop_columns":drop_cols, "num_columns":1, "num_rows":1}))
"""

model_args = all_tests

max_len = max([len(model_arg[0]) for model_arg in model_args])
def compute(model_arg):
    result = do_classification(**model_arg[1])
    train, validation = result.get_accuracy(verbose=False)
    prediction_error = result.get_average_prediction_error()

    return ("| {key:{max_len}} | {train:6.2f}% | {val:6.2f}% | {pred_err:6.2f}% |"
            .format(key=model_arg[0], max_len=max_len, train=train*100, val=validation*100, pred_err=prediction_error*100))

if __name__ == '__main__':
    results = []
    with Pool(PROCESSES) as pool:
        results = pool.map(compute, model_args)

    print("\n\n\nResults:")
    header = "| {0:{max_len}} | {1:>7} | {2:>7} | {3:>7} |".format('MODEL', 'TRN ACC', 'VAL ACC', 'AVG ERR', max_len=max_len)
    print("-"*len(header))
    print(header)
    [print(result) for result in sorted(results)]
    print("-"*len(header))
